name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.6
  get_it: ^7.6.7
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:    
    - lib/images/
